travis:
  secure:
    BINSTAR_TOKEN: VKLCSrZ+FGyak6bKy/p59cWNWKofpRSL2PwKDKwJ2t21StEpHPSO4aopA3gmRlbZybJI+iOXRhLBFnTrIcItOUvI4Dm9qU3vGTgl4rjzwHxXvjXsoN3WIpmMivGzcvddlAhjpdEI21JAjNh6gD+ROe2Ta2S92FbmiXX3YjmlUx+vudPIxQVUjYBr6qlbnKSkJTrtvZf/HuDcPFYYyev5tQnVIXVuDcwxcuc20m4UpePA2igCOU9pHS3mqs1RQ0Jx8jW91y9jKqauCwojSBmkjK4dwpu1iqEMwMgBVG3UNJEg80XWJu7gTrD5j/gdKWe3/gG/zl6A0z1ZvMlR4dJxEJw11i3V7rhSJX1Cgi4FAUzQGSXnctSPvF67vQpjl1zKuVEfW7GRqORqXSdIoz2w8+es5k1ulKFV4pr0kwAl4vFR7aYca9P7uX2+s3fVVMCrkQe14fMZSnIxI0ed8483UKUmfrouOBEWGELugIYvKng6bCkJoMcwUQl1VOb6s+jmLI0PvLaKurjpIg+/urw0Yamr77O0aGkDKLZKNWno0at0DPFMO6YUiT6FLgubJNk7PwuPF+kee+EV4t/i1zUceRsV2hl2wYKQTtv9QuBSAVeTAmUpbC+uhlDfRlgh4DuzT+cE9kYbtZNGBkAs+OW5pgJl6BsILNUsIbmoMe37tjU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
