travis:
  secure:
    BINSTAR_TOKEN: p12KXJ1OVgBr6nupgC4HmHUl7QRdOiOTDPmuqRKmHxL7Tzaol7iVaJt7q+gFa7tTtZ9M58r5Yd2UMaBWXqz/O56EKN3/ESPN8N7KvpY2yVCrfCnBz+Gr8g5jyW7nuRBISft4iFfp6NS0GjLf8PCgC9kZ93sYIF+eT1Lvdjr+zPzqcMluYGJ9d3Y2COZ8hXXuaen8OI5HKKWQkFwAFh3MhfkYi2QRmv8C86XOTuRyxAKIkwcpjw/v4KvAtpMEswrsxz2ebJzpqEPfki3686WacZ7qjUQ/40Bpe0XliADguGR/d9mz8nqUT788bM2GZWn0t0N0ww8oglA2COr2KW/kNGjBFOwV8viuSxwkC4g5lC0PlcH0cQY5AYr+6P6U0Hujjife2L2MaRiSDECpbRdJeqxo9HA9fStfp0GNeidTyQQvmlLsgJXrG4JghvYNYStYjGzChxaQPbariaPS29zcRs+GfOWyLBOFk0ogvDy02fjskogMRbFT7rX6r18JjZf7fHp9N9P8mRFu4I1uYaTogYWhhTiU3RCFpANAcknHoesvEMVFJtSX4j65+s91HqePnRxFIHl211f3vVFZHc37K5mroLmwB3V8TRW7HC8XT++z0ovQ1ovJvwuP7YrCLrYJNbqt/piOodSZ2vPAbd609C9EcY2JuRfvqFr27tX45gg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
