appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: hEIPmyK/A1+Y3U41HLUVOtmkG52XHXgLLb+qv+TnUEeJ/5E7SSwprResV+LOFeLbDcQgt/2lOT60imh2xb54KLFdDUg1mKiC8dqcu9mWbYp8dsuqSlN3QIrix1rNUASBLNWP1qpAxWKeeiJkwF1n8P4yxpsyjQKGbGMG4dNKx4oZUwE9vYIDYZ9cgaBHWD5m7CrmSwliM1u6MKSE3CuC0jGz/MGrbwBhdqmalK/HJ125h4gR7XGIPwpW0TxrGKXlkDZaCcnFxFxkiiMA0TShE77DMfChqAO2t09IKRAzWjHWbudNfRyLs2aJdEMbIDMEWDhh0TGCaNMIuyw6asaLFEfeB5GzvwYfWvsvFJuwnh9fkSCGzhq+Axiep1VB5RDezEgYqAPALC0EjonuIaLnyiqAzPIRT+ihLRfMfFE90QCGDJqMBLW0svGt6I+OlhF2bzyRmjSlwIA8TXdJcEy4V+ASAAaUehFPiXRhT5kgoTjZgz1rDczcxi+PNEzQQ3EHPV7OtfmiFDf0Sb/YRmSuNiGZI2sLrooO5/N3n3mEs5SCNfz5wOnmWjer1OFqxDoqEC9swLLg5/Uq1vPuCYlxg4MyzMY3S4s5TLFkiztK7aCKYliTbm5Ew7VLGaMs7mF9UFA8d7aHblijoYshgu9J8ZJ3LIm/1EJncc0zbnbzQKg=
conda_forge_output_validation: true
